require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'gobarber' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'gobarberTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
  use_flipper!({'Flipper' => '0.79.0'}) # should match the version of your Flipper client app
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'gobarber-tvOS' do
  # Pods for gobarber-tvOS

  target 'gobarber-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
